import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import {
  Box,
  Stack,
  Grid,
  Typography,
  IconButton,
  Card,
  CardContent,
  Avatar,
} from "@mui/material";

import InstagramIcon from "@mui/icons-material/Instagram";
import FacebookIcon from "@mui/icons-material/Facebook";
import MoreVertIcon from "@mui/icons-material/MoreVert";
import CloseIcon from "@mui/icons-material/Close";

export default function Home() {
  const [moreAction, setMoreAction] = useState(false);
  useEffect(() => {
    const video = document.querySelector("#vid-bg").play();
    window.addEventListener("load", function () {
      // Set a timeout...
      setTimeout(function () {
        // Hide the address bar!
        window.scrollTo(0, 1);
      }, 0);
    });
  });

  function handleMoreActionOpen() {
    setMoreAction(true);
  }

  function handleMoreActionClose() {
    setMoreAction(false);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <video id="vid-bg" autoplay muted loop playsInline>
        <source src="vidBg3.mp4" type="video/mp4" />
      </video>
      <Card
        sx={{
          background:
            "linear-gradient(rgb(0,0,0,1)0%,rgb(0,0,0,0.5)30%,rgb(0,0,0,0.0)100%)",
          boxShadow: "inherit",
          backdropFilter: "blur(0px)",
        }}
      >
        <CardContent
          sx={{
            padding: (theme) => theme.spacing(6),
            height: "100vh",
            backgroundColor: "none",
          }}
        >
          <Stack
            direction="column"
            justifyContent="flex-start"
            alignItems="center"
            spacing={3}
            sx={{ height: "inherit" }}
          >
            <Avatar sx={{ width: "150px", height: "150px", fontSize: "50px" }}>
              Tyty
            </Avatar>
            <Stack
              direction="column"
              justifyContent="center"
              alignItems="center"
              spacing={1}
            >
              <Typography variant="h5" fontWeight="bold" color="white">
                Tran Tyty
              </Typography>
              <Stack
                direction="row"
                justifyContent="center"
                alignItems="center"
                spacing={3}
              >
                <IconButton
                  size="large"
                  component="a"
                  target="_blank"
                  href="https://www.facebook.com/tytran.tytran104"
                >
                  <FacebookIcon
                    sx={{ color: "white", width: "30px", height: "30px" }}
                  />
                </IconButton>
                <IconButton
                  size="large"
                  component="a"
                  target="_blank"
                  href="https://www.instagram.com/wychin.chywin/"
                >
                  <InstagramIcon
                    sx={{ color: "white", width: "30px", height: "30px" }}
                  />
                </IconButton>
                <IconButton
                  onClick={() => {
                    handleMoreActionOpen();
                  }}
                  sx={{ position: "relative" }}
                >
                  <MoreVertIcon
                    sx={{ color: "white", width: "30px", height: "30px" }}
                  />
                
                </IconButton>
              </Stack>
            </Stack>
          </Stack>
        </CardContent>
      </Card>
    </div>
  );
}
