import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  Box,
  Stack,
  Grid,
  Typography,
  IconButton,
  Card,
  CardContent,
  Avatar,
} from "@mui/material";

import InstagramIcon from "@mui/icons-material/Instagram";
import FacebookIcon from "@mui/icons-material/Facebook";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card sx={{ backgroundColor: "inherit", boxShadow: "inherit" }}>
        <CardContent sx={{ padding: (theme) => theme.spacing(6) }}>
          <Stack
            direction="column"
            justifyContent="center"
            alignItems="center"
            spacing={3}
          >
            <Avatar sx={{ width: "150px", height: "150px", fontSize: "100px" }}>
              T
            </Avatar>
            <Stack
              direction="column"
              justifyContent="center"
              alignItems="center"
              spacing={1}
            >
              <Typography variant="h5" fontWeight="bold" color="white">
                Tran Tyty
              </Typography>
              <Stack
                direction="row"
                justifyContent="center"
                alignItems="center"
                spacing={3}
              >
                <IconButton
                  size="large"
                  component="a"
                  href="https://www.facebook.com/tytran.tytran104"
                >
                  <FacebookIcon
                    sx={{ color: "white", width: "30px", height: "30px" }}
                  />
                </IconButton>
                <IconButton
                  size="large"
                  component="a"
                  href="https://www.instagram.com/wychin.chywin/"
                >
                  <InstagramIcon
                    sx={{ color: "white", width: "30px", height: "30px" }}
                  />
                </IconButton>
              </Stack>
            </Stack>
          </Stack>
        </CardContent>
      </Card>
    </div>
  );
}
